In [20]:
import pandas as pd
import numpy as np

In [56]:
df = pd.read_csv('stocks_sample.csv', index_col=0)
df

,date,open,high,low,close,volume,adjusted_close,name
0,2000-01-03,116.03,116.03,113.00,113.50,1278800.0,113.50,dia
1,2000-01-04,112.28,112.97,109.77,109.77,1534700.0,109.77,dia
2,2000-01-05,110.00,112.38,109.03,111.19,2007000.0,111.19,dia
3,2000-01-06,111.41,113.17,111.19,112.19,2639200.0,112.19,dia
4,2000-01-07,111.41,115.56,113.31,115.50,3767400.0,115.50,dia
5,2000-01-10,116.81,116.81,115.44,116.00,762900.0,116.00,dia
6,2000-01-11,115.16,116.75,115.02,115.14,1658700.0,115.14,dia
7,2000-01-12,115.50,116.19,115.16,115.44,813300.0,115.44,dia
8,2000-01-13,116.02,116.62,115.22,115.88,1192200.0,115.88,dia
9,2000-01-14,117.47,117.50,116.12,117.50,1935500.0,117.50,dia
10,2000-01-18,116.44,116.88,115.50,115.72,656500.0,115.72,dia
11,2000-01-19,115.62,115.80,114.59,115.56,1003400.0,115.56,dia
12,2000-01-20,115.94,115.97,112.66,113.73,887000.0,113.73,dia
13,2000-01-21,114.19,114.19,112.31,112.81,783200.0,112.81,dia
14,2000-01-24,113.25,113.62,109.06,110.00,2066100.0,110.00,dia
15,2000-01-25,110.59,110.88,108.75,110.34,1728200.0,110.34,dia
16,2000-01-26,110.22,111.38,110.12,110.47,1001400.0,110.47,dia
17,2000-01-27,111.12,111.61,109.19,110.47,853900.0,110.47,dia
18,2000-01-28,109.84,110.06,107.14,107.41,1253300.0,107.41,dia
19,2000-01-31,107.14,109.62,107.00,109.50,996600.0,109.50,dia
20,2000-02-01,109.56,110.72,109.03,110.28,786500.0,110.28,dia
21,2000-02-02,110.38,111.19,109.66,109.69,618100.0,109.69,dia
22,2000-02-03,110.62,110.66,108.22,110.50,863300.0,110.50,dia
23,2000-02-04,110.44,110.97,109.34,109.75,474000.0,109.75,dia
24,2000-02-07,109.16,109.47,108.38,108.75,723900.0,108.75,dia
25,2000-02-08,109.91,110.34,109.12,109.31,993100.0,109.31,dia
26,2000-02-09,109.38,109.38,106.78,106.91,819900.0,106.91,dia
27,2000-02-10,107.27,107.59,106.02,107.00,1263500.0,107.00,dia
28,2000-02-11,106.56,106.56,103.62,104.50,2148400.0,104.50,dia
29,2000-02-14,105.00,105.59,104.56,105.50,1300800.0,105.50,dia
...,...,...,...,...,...,...,...,...
970,2003-11-07,99.18,99.51,98.11,98.11,4625800.0,98.11,dia
971,2003-11-10,98.32,98.50,97.60,97.81,4549400.0,97.81,dia
972,2003-11-11,97.55,97.93,97.43,97.62,3328500.0,97.62,dia
973,2003-11-12,97.69,98.95,97.66,98.80,6068900.0,98.80,dia
974,2003-11-13,98.86,98.91,98.28,98.72,4014400.0,98.72,dia
975,2003-11-14,98.70,99.30,97.74,97.97,5114400.0,97.97,dia
976,2003-11-17,97.51,97.71,96.63,97.47,5893500.0,97.47,dia
977,2003-11-18,97.71,97.90,96.47,96.60,4659500.0,96.60,dia
978,2003-11-19,96.83,97.53,96.60,97.38,4029600.0,97.38,dia
979,2003-11-20,96.86,97.70,96.39,96.54,6709600.0,96.54,dia
980,2003-11-21,96.62,96.62,95.27,96.49,4717000.0,96.49,dia
981,2003-11-24,96.90,97.65,96.55,97.47,4770900.0,97.47,dia
982,2003-11-25,97.72,98.07,97.37,97.68,5553500.0,97.68,dia
983,2003-11-26,98.08,98.15,97.15,97.90,3963700.0,97.90,dia
984,2003-11-28,97.64,98.16,97.64,98.02,855900.0,98.02,dia
985,2003-12-01,98.37,99.16,98.32,99.10,5722400.0,99.10,dia
986,2003-12-02,98.93,99.04,98.51,98.75,3588500.0,98.75,dia
987,2003-12-03,98.90,99.59,98.85,98.95,6184400.0,98.95,dia
988,2003-12-04,99.19,99.52,98.86,99.45,6048600.0,99.45,dia
989,2003-12-05,99.25,99.33,98.59,98.80,5332400.0,98.80,dia
990,2003-12-08,98.55,99.85,98.52,99.81,4715100.0,99.81,dia
991,2003-12-09,100.00,100.15,96.64,99.45,8956900.0,99.45,dia
992,2003-12-10,99.35,99.77,98.98,99.60,5518900.0,99.60,dia
993,2003-12-11,99.65,100.43,99.52,100.38,6635700.0,100.38,dia
994,2003-12-12,100.40,100.77,99.93,100.63,5781600.0,100.63,dia
995,2003-12-15,101.64,101.99,100.20,100.45,7400100.0,100.45,dia
996,2003-12-16,100.46,101.56,100.46,101.50,5883900.0,101.50,dia
997,2003-12-17,101.32,101.86,101.11,101.86,4729900.0,101.86,dia
998,2003-12-18,101.87,102.83,101.70,102.81,10436600.0,102.81,dia
999,2003-12-19,102.60,103.07,102.38,102.74,9837100.0,102.74,dia

In [69]:
def is_max(x):
    return True if x.max() == x[-1] else False
def is_min(x):
    return True if x.min() == x[-1] else False



df['max_28'] = df['adjusted_close'].rolling(28).apply(is_max)
df['min_28'] = df['adjusted_close'].rolling(28).apply(is_min)

df['label_down'] = df['min_28']
df['label_up'] = df['max_28']
df['label_hold'] = 0.0
df.loc[(df['label_down'] != 1.0) & (df['label_up'] != 1.0), 'label_hold'] = 1.0

In [70]:
df

,date,open,high,low,close,volume,adjusted_close,name,max_28,min_28,label_down,label_up,label_hold
0,2000-01-03,116.03,116.03,113.00,113.50,1278800.0,113.50,dia,NaN,NaN,NaN,NaN,1.0
1,2000-01-04,112.28,112.97,109.77,109.77,1534700.0,109.77,dia,NaN,NaN,NaN,NaN,1.0
2,2000-01-05,110.00,112.38,109.03,111.19,2007000.0,111.19,dia,NaN,NaN,NaN,NaN,1.0
3,2000-01-06,111.41,113.17,111.19,112.19,2639200.0,112.19,dia,NaN,NaN,NaN,NaN,1.0
4,2000-01-07,111.41,115.56,113.31,115.50,3767400.0,115.50,dia,NaN,NaN,NaN,NaN,1.0
5,2000-01-10,116.81,116.81,115.44,116.00,762900.0,116.00,dia,NaN,NaN,NaN,NaN,1.0
6,2000-01-11,115.16,116.75,115.02,115.14,1658700.0,115.14,dia,NaN,NaN,NaN,NaN,1.0
7,2000-01-12,115.50,116.19,115.16,115.44,813300.0,115.44,dia,NaN,NaN,NaN,NaN,1.0
8,2000-01-13,116.02,116.62,115.22,115.88,1192200.0,115.88,dia,NaN,NaN,NaN,NaN,1.0
9,2000-01-14,117.47,117.50,116.12,117.50,1935500.0,117.50,dia,NaN,NaN,NaN,NaN,1.0
10,2000-01-18,116.44,116.88,115.50,115.72,656500.0,115.72,dia,NaN,NaN,NaN,NaN,1.0
11,2000-01-19,115.62,115.80,114.59,115.56,1003400.0,115.56,dia,NaN,NaN,NaN,NaN,1.0
12,2000-01-20,115.94,115.97,112.66,113.73,887000.0,113.73,dia,NaN,NaN,NaN,NaN,1.0
13,2000-01-21,114.19,114.19,112.31,112.81,783200.0,112.81,dia,NaN,NaN,NaN,NaN,1.0
14,2000-01-24,113.25,113.62,109.06,110.00,2066100.0,110.00,dia,NaN,NaN,NaN,NaN,1.0
15,2000-01-25,110.59,110.88,108.75,110.34,1728200.0,110.34,dia,NaN,NaN,NaN,NaN,1.0
16,2000-01-26,110.22,111.38,110.12,110.47,1001400.0,110.47,dia,NaN,NaN,NaN,NaN,1.0
17,2000-01-27,111.12,111.61,109.19,110.47,853900.0,110.47,dia,NaN,NaN,NaN,NaN,1.0
18,2000-01-28,109.84,110.06,107.14,107.41,1253300.0,107.41,dia,NaN,NaN,NaN,NaN,1.0
19,2000-01-31,107.14,109.62,107.00,109.50,996600.0,109.50,dia,NaN,NaN,NaN,NaN,1.0
20,2000-02-01,109.56,110.72,109.03,110.28,786500.0,110.28,dia,NaN,NaN,NaN,NaN,1.0
21,2000-02-02,110.38,111.19,109.66,109.69,618100.0,109.69,dia,NaN,NaN,NaN,NaN,1.0
22,2000-02-03,110.62,110.66,108.22,110.50,863300.0,110.50,dia,NaN,NaN,NaN,NaN,1.0
23,2000-02-04,110.44,110.97,109.34,109.75,474000.0,109.75,dia,NaN,NaN,NaN,NaN,1.0
24,2000-02-07,109.16,109.47,108.38,108.75,723900.0,108.75,dia,NaN,NaN,NaN,NaN,1.0
25,2000-02-08,109.91,110.34,109.12,109.31,993100.0,109.31,dia,NaN,NaN,NaN,NaN,1.0
26,2000-02-09,109.38,109.38,106.78,106.91,819900.0,106.91,dia,NaN,NaN,NaN,NaN,1.0
27,2000-02-10,107.27,107.59,106.02,107.00,1263500.0,107.00,dia,0.0,0.0,0.0,0.0,1.0
28,2000-02-11,106.56,106.56,103.62,104.50,2148400.0,104.50,dia,0.0,1.0,1.0,0.0,0.0
29,2000-02-14,105.00,105.59,104.56,105.50,1300800.0,105.50,dia,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,2003-11-07,99.18,99.51,98.11,98.11,4625800.0,98.11,dia,0.0,0.0,0.0,0.0,1.0
971,2003-11-10,98.32,98.50,97.60,97.81,4549400.0,97.81,dia,0.0,0.0,0.0,0.0,1.0
972,2003-11-11,97.55,97.93,97.43,97.62,3328500.0,97.62,dia,0.0,0.0,0.0,0.0,1.0
973,2003-11-12,97.69,98.95,97.66,98.80,6068900.0,98.80,dia,0.0,0.0,0.0,0.0,1.0
974,2003-11-13,98.86,98.91,98.28,98.72,4014400.0,98.72,dia,0.0,0.0,0.0,0.0,1.0
975,2003-11-14,98.70,99.30,97.74,97.97,5114400.0,97.97,dia,0.0,0.0,0.0,0.0,1.0
976,2003-11-17,97.51,97.71,96.63,97.47,5893500.0,97.47,dia,0.0,0.0,0.0,0.0,1.0
977,2003-11-18,97.71,97.90,96.47,96.60,4659500.0,96.60,dia,0.0,0.0,0.0,0.0,1.0
978,2003-11-19,96.83,97.53,96.60,97.38,4029600.0,97.38,dia,0.0,0.0,0.0,0.0,1.0
979,2003-11-20,96.86,97.70,96.39,96.54,6709600.0,96.54,dia,0.0,0.0,0.0,0.0,1.0
980,2003-11-21,96.62,96.62,95.27,96.49,4717000.0,96.49,dia,0.0,0.0,0.0,0.0,1.0
981,2003-11-24,96.90,97.65,96.55,97.47,4770900.0,97.47,dia,0.0,0.0,0.0,0.0,1.0
982,2003-11-25,97.72,98.07,97.37,97.68,5553500.0,97.68,dia,0.0,0.0,0.0,0.0,1.0
983,2003-11-26,98.08,98.15,97.15,97.90,3963700.0,97.90,dia,0.0,0.0,0.0,0.0,1.0
984,2003-11-28,97.64,98.16,97.64,98.02,855900.0,98.02,dia,0.0,0.0,0.0,0.0,1.0
985,2003-12-01,98.37,99.16,98.32,99.10,5722400.0,99.10,dia,1.0,0.0,0.0,1.0,0.0
986,2003-12-02,98.93,99.04,98.51,98.75,3588500.0,98.75,dia,0.0,0.0,0.0,0.0,1.0
987,2003-12-03,98.90,99.59,98.85,98.95,6184400.0,98.95,dia,0.0,0.0,0.0,0.0,1.0
988,2003-12-04,99.19,99.52,98.86,99.45,6048600.0,99.45,dia,1.0,0.0,0.0,1.0,0.0
989,2003-12-05,99.25,99.33,98.59,98.80,5332400.0,98.80,dia,0.0,0.0,0.0,0.0,1.0
990,2003-12-08,98.55,99.85,98.52,99.81,4715100.0,99.81,dia,1.0,0.0,0.0,1.0,0.0
991,2003-12-09,100.00,100.15,96.64,99.45,8956900.0,99.45,dia,0.0,0.0,0.0,0.0,1.0
992,2003-12-10,99.35,99.77,98.98,99.60,5518900.0,99.60,dia,0.0,0.0,0.0,0.0,1.0
993,2003-12-11,99.65,100.43,99.52,100.38,6635700.0,100.38,dia,1.0,0.0,0.0,1.0,0.0
994,2003-12-12,100.40,100.77,99.93,100.63,5781600.0,100.63,dia,1.0,0.0,0.0,1.0,0.0
995,2003-12-15,101.64,101.99,100.20,100.45,7400100.0,100.45,dia,0.0,0.0,0.0,0.0,1.0
996,2003-12-16,100.46,101.56,100.46,101.50,5883900.0,101.50,dia,1.0,0.0,0.0,1.0,0.0
997,2003-12-17,101.32,101.86,101.11,101.86,4729900.0,101.86,dia,1.0,0.0,0.0,1.0,0.0
998,2003-12-18,101.87,102.83,101.70,102.81,10436600.0,102.81,dia,1.0,0.0,0.0,1.0,0.0
999,2003-12-19,102.60,103.07,102.38,102.74,9837100.0,102.74,dia,0.0,0.0,0.0,0.0,1.0

In [78]:
arr = 'holey'

In [77]:
arr[a:b:c]

NameError: name 'arr' is not defined

In [87]:
# c=1
# -------------------------------------------------
# If a is omitted then you start as far as possible 
# in the direction you're counting from 
# (so that's the start if c is positive and the end if negative)
# -------------------------------------------------
# If b is omitted then you end as far as possible 
# in the direction you're counting to 
# (so that's the end if c is positive and the start if negative). 
# -------------------------------------------------
# If a or b is negative it's an offset from the end 
# (-1 being the last character) instead of the start.
arr[-1::-1]

'yeloh'

In [88]:
df_1 = pd.DataFrame({'a':[1,2,3], 'b':[5,8,9]})

In [89]:
df_1

   a  b
0  1  5
1  2  8
2  3  9

In [92]:
df_2 = pd.DataFrame({'c':[1,2], 'd':[5,8]})
df_2

   c  d
0  1  5
1  2  8

In [98]:
pd.concat((df_1, df_2), axis=1)

   a  b    c    d
0  1  5  1.0  5.0
1  2  8  2.0  8.0
2  3  9  NaN  NaN